language: python
virtualenv: 
  system_site_packages: true
sudo: false
addons:
  apt:
    packages:
    - yum
    - python-rpm
script: 
  - pep8 --show-source --show-pep8 setup.py planex tests
  - pylint setup.py planex
  - nosetests
